Feature/user/#10
four-four-four/DAMOA-Backend pull request #12
Opened 2021-12-19 17:03 UTC by zlzzlzz2l

# [User] 이메일 & 닉네임 중복 체크 기능 개발

이메일과 닉네임 중복 체크 API를 추가했습니다.

## 이메일 중복 체크
이메일 중복일 때
![image](https://user-images.githubusercontent.com/48669011/146683584-be8c91d5-204c-4691-9341-dbd273d78b33.png)

이메일 중복이 아닐 때
![image](https://user-images.githubusercontent.com/48669011/146683597-9681051a-b848-451f-98c3-1e3ade1f421d.png)

## 닉네임 중복 체크
닉네임 중복일 때
![image](https://user-images.githubusercontent.com/48669011/146683729-a80247a5-4d34-4b0a-945e-a0e7813dcbb0.png)

닉네임 중복이 아닐 때
![image](https://user-images.githubusercontent.com/48669011/146683738-b8365e66-a98f-49fd-9f48-e9df53c61a8f.png)

### 이메일 중복 체크 API
![image](https://user-images.githubusercontent.com/48669011/146683789-ab4f8bbf-0594-4c83-9237-7c17d842134f.png)
![image](https://user-images.githubusercontent.com/48669011/146683797-21141ca7-a3df-4485-a017-0a136abed23f.png)

### 닉네임 중복 체크 API
![image](https://user-images.githubusercontent.com/48669011/146683810-704a2efa-c648-4b67-93ba-3ba056f66e0d.png)
![image](https://user-images.githubusercontent.com/48669011/146683814-e43b23f7-3545-42de-8e68-853e8786f06c.png)

2021-12-19 17:53 UTC, 0xe82de commented
api 매핑 경로를 "api/v1/users" 로 수정해주세요~!

2021-12-19 17:59 UTC, zlzzlzz2l commented
> api 매핑 경로를 "api/v1/users" 로 수정해주세요~!

2021-12-20 03:29 UTC, yjs1213 approved these changes
고생하셨습니다~

2021-12-20 17:14 UTC, 0xe82de requested changes
코멘트입니다.

2021-12-20 17:14 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/controller/user/UserController.java
> +    @PostMapping("/email/{userEmail}/exists")
@GetMapping으로 바꾸면 어떨까요?

2021-12-20 17:14 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/controller/user/UserController.java
> +    @PostMapping("/nickname/{userNickname}/exists")
이 부분도 @GetMapping으로 바꾸면 어떨까요?

2021-12-20 17:14 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +
회원 가입 전 회원 객체와 Dao로 가져온 회원 객체를 비교하는 게 좋을 것 같습니다.

2021-12-20 17:14 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +
위 로직 밑에서 DB에 회원 정보를 넣은 다음 중복 체크하는 로직을 추가하면 좋을 것 같습니다.

2021-12-20 17:14 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +    }
이메일 중복 테스트 코드와 마찬가지로 위 로직 밑에서 회원 가입 후 닉네임 중복 체크 로직을 추가하면 좋을 것 같습니다.

2021-12-20 17:14 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/service/user/UserServiceImplTest.java
> +        Assertions.assertThat(resultNickname).isFalse(); // False라면 중복되지 않기 때문에 가입 가능
Dao 테스트와 마찬가지로 회원 가입 전의 객체와 Dao에서 가져온 객체를 비교하는 로직을 추가해야 할 것 같습니다.

2021-12-20 17:14 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/service/user/UserServiceImplTest.java
> +        Assertions.assertThat(result).isTrue(); // True일 때 중복
Dao 테스트 코드 코멘트와 마찬가지로 회원 정보를 DB에 넣은 후 중복 체크하는 로직을 추가하면 좋을 것 같습니다.

2021-12-20 17:14 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/service/user/UserServiceImplTest.java
> +        Assertions.assertThat(result).isTrue(); // True일 때 중복
Dao 테스트 코드 코멘트와 마찬가지로 회원 정보를 DB에 넣은 후 중복 체크하는 로직을 추가하면 좋을 것 같습니다.

2021-12-20 17:45 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/controller/user/UserController.java
> +    @PostMapping("/email/{userEmail}/exists")
반영하겠습니다.

2021-12-20 17:45 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/controller/user/UserController.java
> +    @PostMapping("/nickname/{userNickname}/exists")
반영했습니다.

2021-12-21 12:00 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +
반영했습니다.

2021-12-21 12:58 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +
반영했습니다.

2021-12-21 12:59 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +    }
반영했습니다.

2021-12-21 13:06 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/service/user/UserServiceImplTest.java
> +        Assertions.assertThat(resultNickname).isFalse(); // False라면 중복되지 않기 때문에 가입 가능
반영했습니다.

2021-12-21 13:28 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/service/user/UserServiceImplTest.java
> +        Assertions.assertThat(result).isTrue(); // True일 때 중복
반영했습니다.

2021-12-21 13:30 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/service/user/UserServiceImplTest.java
> +        Assertions.assertThat(result).isTrue(); // True일 때 중복
반영했습니다.

Dao와 서비스 테스트에서 이메일과 닉네임 메서드는 이메일이나 닉네임 중복 체크 후, 회원가입을 진행하는 로직으로 구성했습니다.

2021-12-21 15:03 UTC, 0xe82de requested changes
리뷰 확인해주시고 바꿀 게 있으면 바꾸시면 될 것 같아요 :)

2021-12-21 15:03 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +        Assertions.assertThat(user).isEqualTo(result);
다음 테스트 메서드 작성할 때를 위해서 `Assertions`를 `static import`로 빼면 좋을 것 같아요.

2021-12-21 15:03 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +        String result = userDao.selectEmailByEmail(user.getUserEmail()); // 이메일 중복 체크
`result`가 `null` 인지 체크하면 좋을 것 같습니다.

2021-12-21 15:03 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +        }
윗 부분 로직에서 `result`가 `null`일 때 회원 가입을 진행하고, 그 뒤에 다시 이메일 중복체크를 위해 `userDao.selectEmail()` 메서드를 호출했을 때 `null`이 아닌지 체크하는게 좋을 것 같습니다.

2021-12-21 15:03 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +        String result = userDao.selectByNickname(user.getUserNickname()); // 이메일 중복 체크
주석이 잘못 작성된 것 같네요.

2021-12-21 15:03 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +        }
이 테스트 메서드도 이메일 테스트 메서드 코멘트와 같이 수정하면 좋을 것 같습니다.

2021-12-21 15:03 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/service/user/UserServiceImplTest.java
> +        }
`Dao` 테스트 코멘트와 마찬가지로 `result`가 `false`인지 체크하고, 회원가입을 진행한 뒤에 이메일 중복 체크를 하기 위해 `userService.isEmailDuplication()` 메서드 결과가 `true`인지 체크하도록 로직을 수정하며 좋을 것 같습니다.

2021-12-21 15:03 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/model/service/user/UserServiceImplTest.java
> +        }
이메일 코멘트와 동일합니다.

2021-12-21 15:29 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +        Assertions.assertThat(user).isEqualTo(result);
반영했습니다.

2021-12-21 17:22 UTC, 0xe82de requested changes
리뷰 추가합니다 :)

2021-12-21 17:22 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/model/dao/user/UserDao.java
> +    UserDto selectUser(long integer);
테스트 코드에서 `user` 객체를 가져오기 위해 `selectUser` 메서드를 추가하신 것 같은데 바로 위에 `selectByUserEmail` 메서드로 `user` 객체를 가져올 수 있습니다. `userIdx`로 `user` 객체를 가져와야 하는 이유가 있는게 아니라면 기존의 메서드를 활용하는게 좋을 것 같습니다~ 만약 `selectByUserEmail` 메서드를 사용하신다면 메서드 이름을 `selectUserByUserEmail`로 리팩토링해주시면 감사합니다~

만약 새롭게 추가하신 `selectUser` 메서드 사용하셔야 한다면 아래 내용을 고려해주세요~!

메서드 이름 : `selectUserByUserIdx`
매개변수 타입 : `Long`
매개변수 이름 : `userIdx`

2021-12-22 15:24 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +        String result = userDao.selectEmailByEmail(user.getUserEmail()); // 이메일 중복 체크
반영했습니다.

2021-12-22 15:24 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +        }
반영했습니다.

2021-12-22 15:24 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +        String result = userDao.selectByNickname(user.getUserNickname()); // 이메일 중복 체크
반영했습니다.

2021-12-22 15:24 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
> +        }
반영했습니다.

2021-12-22 15:24 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/service/user/UserServiceImplTest.java
> +        }
반영했습니다.

2021-12-22 15:24 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/model/service/user/UserServiceImplTest.java
> +        }
반영했습니다.

2021-12-22 15:25 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/model/dao/user/UserDao.java
> +    UserDto selectUser(long integer);
selectByEmail 메서드를 이용하는 게 나을 것 같아서 리뷰 토대로 반영했습니다.

2021-12-23 12:41 UTC, 0xe82de approved these changes
고생하셨습니다!!!

2021-12-23 12:58 UTC, yjs1213 approved these changes
고생하셨습니다~

2021-12-23 16:21 UTC, merged