Refactor/user/#15
four-four-four/DAMOA-Backend pull request #18
Opened 2022-01-24 16:23 UTC by zlzzlzz2l

# [유저] 이메일 & 닉네임 중복 체크 기능 리팩토링

---

이메일과 닉네임 중복 체크 기능을 리팩토링하였습니다.

---

이메일 중복일 때
![image](https://user-images.githubusercontent.com/48669011/150821464-9c0bfac4-a7a2-40c8-878d-6a1cebdb884c.png)

이메일 중복이 아닐 때
![image](https://user-images.githubusercontent.com/48669011/150821353-1999917c-c3e9-4ed8-b3d1-ca8eaebeaca3.png)

닉네임 중복일 때
![image](https://user-images.githubusercontent.com/48669011/150821288-849c5475-7217-43df-96f6-29b8512df710.png)

닉네임 중복이 아닐 때
![image](https://user-images.githubusercontent.com/48669011/150821251-b1b87c8d-1466-44b0-8e9d-0c316bdbf0a3.png)

2022-01-24 16:32 UTC, 0xe82de requested changes
리뷰 확인해주세요~ 고생하셨습니다.

2022-01-24 16:32 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/api/member/repository/MemberRepository.java
> +    int countByNickname(String memberNickname);
count 대신 exists를 사용하는 것이 좋을 것 같습니다 :)

[참고 링크](https://velog.io/@pjh612/JPQL%EC%9D%98-count-%EC%84%B1%EB%8A%A5-%EC%9D%B4%EC%8A%88-%EB%B0%8F-exist-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95)

2022-01-24 16:32 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/api/member/service/MemberService.java
> +    boolean isNicknameDuplication(String memberNickname);
변수 이름에 member를 제거해도 괜찮을 것 같습니다. :)

2022-01-24 16:32 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/api/member/service/MemberServiceImpl.java
MembeDao를 사용하지 않는다면 삭제하는 것도 좋을 것 같아요. :)

2022-01-24 16:32 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/api/member/service/MemberServiceImpl.java
> +        return memberRepository.countByNickname(memberNickname) != 0;
spring data jpa 메서드를 exists로 바꾸시면 이 부분도 수정되어야 할 것 같습니다. :)

2022-01-24 17:10 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/api/member/repository/MemberRepository.java
> +    int countByNickname(String memberNickname);
반영했습니다.

2022-01-24 17:12 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/api/member/service/MemberService.java
> +    boolean isNicknameDuplication(String memberNickname);
반영했습니다.

2022-01-24 17:15 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/api/member/service/MemberServiceImpl.java
MemberDao를 삭제하면 내부 코드에서 오류가 발생합니다. 

유저 리팩토링을 진행하면서 삭제하도록 하겠습니다.

2022-01-24 17:21 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/api/member/service/MemberServiceImpl.java
> +        return memberRepository.countByNickname(memberNickname) != 0;
반영했습니다.

2022-01-25 04:03 UTC, 0xe82de approved these changes

2022-01-25 10:46 UTC, yjs1213 approved these changes
고생하셨습니다~

2022-01-25 15:05 UTC, merged