Refactor/user/#21
four-four-four/DAMOA-Backend pull request #24
Opened 2022-02-05 18:00 UTC by zlzzlzz2l

# [유저] Validation 리팩토링 #21 

- Validation을 리팩토링한 후, 이메일과 닉네임 중복 체크 테스트를 작성하였습니다.

---

- 닉네임 Validation 리팩토링
- 비밀번호 Validation 추가
- 이메일 & 닉네임 중복 체크 테스트 작성

2022-02-06 03:09 UTC, 0xe82de requested changes
전반적으로 리팩토링하시고 다시 올려주세요

2022-02-08 10:23 UTC, 0xe82de requested changes
코멘트 확인해주시고 피드백 주세요 :)

2022-02-08 10:23 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/api/member/controller/MemberController.java
sout 다 지워 주세요 :)

2022-02-08 10:23 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/api/member/dto/req/ReqRegisterMemberDto.java
>      private String nickname;
길이 제한이 적용된 것인가요?

2022-02-08 10:23 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/api/member/dto/req/ReqRegisterMemberDto.java
gender, birthDate, job, role 모두 valid 처리해주세요

2022-02-08 14:04 UTC, yjs1213 approved these changes
고생하셨습니다~

2022-02-09 16:48 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/api/member/controller/MemberController.java
반영했습니다.

2022-02-09 16:51 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/api/member/dto/req/ReqRegisterMemberDto.java
>      private String nickname;
길이 제한이 적용된 정규표현식으로 수정하였습니다.

2022-02-10 06:59 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/api/member/dto/req/ReqRegisterMemberDto.java
반영했습니다.

2022-02-10 11:13 UTC, 0xe82de approved these changes
고생하셨습니다 :)

2022-02-10 12:11 UTC, merged