Feature/admin/#32
four-four-four/DAMOA-Backend pull request #34
Opened 2022-03-25 22:55 UTC by zlzzlzz2l

# [관리자] 공지사항 등록 개발

---

공지사항 등록 API를 추가하였습니다.

---
올바른 형식으로 공지사항을 등록했을 때
![image](https://user-images.githubusercontent.com/48669011/160212061-801f4e56-ce37-4fc3-ba45-1fe93b859313.png)

제목 혹은 본문이 빈칸일 때
![image](https://user-images.githubusercontent.com/48669011/160212088-eacdf6a1-ddd0-4f9f-a21b-94ba39a892c7.png)

![image](https://user-images.githubusercontent.com/48669011/160212109-115d8ba1-f501-4979-86e8-e5aed73189bf.png)

2022-03-27 07:13 UTC, 0xe82de requested changes
고생하셨습니다. 코멘트 확인해주시고 피드백 주세요 :)

2022-03-27 07:13 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/api/notice/repository/NoticeRepository.java
> +    Notice findBySeq(@Param("seq") Long seq);
```java
@Query("SELECT n FROM Notice n WHERE n.seq = :seq AND n.isDeleted = FALSE")
Notice findBySeq(@Param("seq") Long seq);
```

공지사항 데이터는 `isDeleted` 컬럼으로 삭제 여부를 관리하기 때문에 위처럼 바꾸는 것이 좋은 것 같아요 :)

2022-03-27 07:13 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/api/notice/service/NoticeServiceImplTest.java
> +
이렇게 했을 때 `delete` 쿼리가 정상적으로 나가나요?? db에 값이 있을 때요.

2022-03-27 07:13 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/api/notice/repository/NoticeRepositoryTest.java
> +
`em.flush()`, `em.clear()` 추가해야되지 않을까 싶습니다.

2022-03-28 13:16 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/api/notice/repository/NoticeRepository.java
> +    Notice findBySeq(@Param("seq") Long seq);
아하 넵넵 반영했습니다!

2022-03-28 13:34 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/api/notice/service/NoticeServiceImplTest.java
> +
임시로 DB에 값을 추가하고 테스트했습니다!
아래 그림과 같이 `DELETE` 쿼리가 정상적으로 나오는 것을 확인할 수 있습니다.

![image](https://user-images.githubusercontent.com/48669011/160408625-9e89a518-591a-4bd2-9887-22bc11122e9c.png)

![image](https://user-images.githubusercontent.com/48669011/160408840-240b6344-5f78-47b7-a9d3-45e93822b16b.png)
![image](https://user-images.githubusercontent.com/48669011/160408916-5c1b2c8d-78c8-43f6-ade3-0b8518366ab6.png)
![image](https://user-images.githubusercontent.com/48669011/160408950-291ba279-804b-43fd-a857-efe36f8453ce.png)

2022-03-29 04:49 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/api/notice/repository/NoticeRepository.java
> +    Notice findBySeq(@Param("seq") Long seq);
임시로 DB에 값을 추가하고 테스트했습니다! 
아래 그림과 같이 DELETE 쿼리가 정상적으로 나오는 것을 확인할 수 있습니다.

![image](https://user-images.githubusercontent.com/48669011/160535448-a6a41882-37d2-4557-8bf3-6111fdc8638e.png)

![image](https://user-images.githubusercontent.com/48669011/160535255-9d34dd7b-c3e7-4303-9188-25ef740a5ec1.png)
![image](https://user-images.githubusercontent.com/48669011/160535278-41d81b14-0a58-4365-9a54-b46494c3a637.png)
![image](https://user-images.githubusercontent.com/48669011/160535316-0f533581-9b33-45ce-afa4-6fa33b24a0dd.png)

2022-03-29 04:53 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/api/notice/service/NoticeServiceImplTest.java
> +
임시로 DB에 값을 추가하고 테스트했습니다! 
아래 그림과 같이 DELETE 쿼리가 정상적으로 나오는 것을 확인할 수 있습니다.

![image](https://user-images.githubusercontent.com/48669011/160535448-a6a41882-37d2-4557-8bf3-6111fdc8638e.png)

![image](https://user-images.githubusercontent.com/48669011/160535255-9d34dd7b-c3e7-4303-9188-25ef740a5ec1.png)
![image](https://user-images.githubusercontent.com/48669011/160535278-41d81b14-0a58-4365-9a54-b46494c3a637.png)
![image](https://user-images.githubusercontent.com/48669011/160535316-0f533581-9b33-45ce-afa4-6fa33b24a0dd.png)

2022-03-29 05:02 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/api/notice/repository/NoticeRepositoryTest.java
> +
넵 반영했습니다.

2022-03-29 05:06 UTC, 0xe82de approved these changes
고생하셨습니다~

2022-03-29 05:11 UTC, yjs1213 approved these changes
고생하셨어요

2022-03-29 07:23 UTC, merged