Feature/user/#35
four-four-four/DAMOA-Backend pull request #38
Opened 2022-03-31 16:44 UTC by zlzzlzz2l

# [유저] 공지사항 댓글 등록 개발 및 공지사항 등록 리팩토링

---

- 공지사항 댓글 등록 API를 추가하였습니다
- 공지사항 등록 API를 수정하였습니다.

---

## 공지사항 댓글 등록

### 공지사항 댓글이 작성되었을 때
![image](https://user-images.githubusercontent.com/48669011/161106429-12556f48-437f-4233-af9b-42388f40cdef.png)

### 댓글에 " " or "" or null이 들어갔을 때
![image](https://user-images.githubusercontent.com/48669011/161106608-65ee944b-bb7f-4cbd-a092-810172bdce8e.png)

![image](https://user-images.githubusercontent.com/48669011/161106649-4139ce88-73d5-450c-99ae-f53e72934b06.png)

![image](https://user-images.githubusercontent.com/48669011/161106713-0e225a3b-3e06-4bea-a7b6-502c03d99918.png)

### 공지사항 데이터가 없을 때
![image](https://user-images.githubusercontent.com/48669011/161106978-bc848203-3c31-4f7b-bfc1-0239b533e95b.png)

2022-03-31 17:31 UTC, 0xe82de requested changes
고생하셨습니다. :) 리뷰 확인해주시고 피드백 주세요.
감사합니다.

2022-03-31 17:31 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/domain/notice/controller/dto/NoticeCommentRequestDto.java
> +        private Long noticeSeq;
데이터가 양수만 들어올 수 있도록 제한하면 좋을 것 같아요.

2022-03-31 17:31 UTC, 0xe82de commented on src/main/java/com/fourfourfour/damoa/domain/notice/controller/NoticeCommentController.java
> +@RequestMapping("/api/v1/notice/comment")
요청 URI를 `/api/v1/notices/{noticeSeq}/comments` 로 바꾸는 것은 어떤가요?

2022-03-31 17:31 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/domain/notice/service/NoticeCommentServiceImplTest.java
> +    private NoticeRequestDto.RegisterDto noticeRegisterDto;
앞으로 추가될 테스트 케이스에서 2개 이상의 테스트용 DTO가 필요하다면 변수명 끝에 숫자를 붙여도 좋을 것 같아요.
```text
adminRegisterDto => adminRegisterDto1
memberRegisterDto => memberRegisterDto1
noticeRegisterDto => noticeRegisterDto1
```

2022-03-31 17:31 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/domain/notice/repository/NoticeCommentRepositoryTest.java
> +    private Notice notice;
앞으로 추가될 테스트 케이스에서 2개 이상의 테스트용 DTO가 필요하다면 변수명 끝에 숫자를 붙여도 좋을 것 같아요.
```text
admin => admin1
member => member1
notice => notice1
```

2022-03-31 17:31 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/domain/notice/service/NoticeServiceImplTest.java
> +    private NoticeRequestDto.RegisterDto noticeRegisterDto;
앞으로 추가될 테스트 케이스에서 2개 이상의 테스트용 DTO가 필요하다면 변수명 끝에 숫자를 붙여도 좋을 것 같아요.
```text
adminRegisterDto => adminRegisterDto1
noticeRegisterDto => noticeRegisterDto1
```

2022-03-31 17:31 UTC, 0xe82de commented on src/test/java/com/fourfourfour/damoa/domain/notice/repository/NoticeRepositoryTest.java
> +    public void noticeRegister() {
메서드가 정상적으로 처리되었을 때 테스트 케이스인 것 같아요. 아래처럼 수정하는 것은 어떨까요?
```java
@DisplayName("공지사항 엔티티 등록 : 성공")
public void noticeRegisterSuccess()
```

2022-04-01 00:28 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/domain/notice/controller/dto/NoticeCommentRequestDto.java
> +        private Long noticeSeq;
반영했습니다!

2022-04-01 15:03 UTC, zlzzlzz2l commented on src/main/java/com/fourfourfour/damoa/domain/notice/controller/NoticeCommentController.java
> +@RequestMapping("/api/v1/notice/comment")
반영했습니다!

2022-04-01 15:37 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/domain/notice/service/NoticeCommentServiceImplTest.java
> +    private NoticeRequestDto.RegisterDto noticeRegisterDto;
반영했습니다!

2022-04-01 15:38 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/domain/notice/repository/NoticeCommentRepositoryTest.java
> +    private Notice notice;
반영했습니다!

2022-04-01 15:38 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/domain/notice/service/NoticeServiceImplTest.java
> +    private NoticeRequestDto.RegisterDto noticeRegisterDto;
반영했습니다!

2022-04-01 15:40 UTC, zlzzlzz2l commented on src/test/java/com/fourfourfour/damoa/domain/notice/repository/NoticeRepositoryTest.java
> +    public void noticeRegister() {
넵 반영했습니다!

2022-04-01 23:11 UTC, yjs1213 approved these changes
고생하셨습니다

2022-04-02 01:12 UTC, 0xe82de approved these changes
고생하셨습니다. :)

2022-04-02 01:17 UTC, merged